#!/bin/bash

git config --global push.default matching

git add pom.xml
git add pom.xml.versionsBackup

git commit -m "Updated POM with release candidate's version number"
git push -u origin `git status | grep "On branch" | cut -d " " -f 3`
